Added instance count loop
lanets/terraform-vsphere-vms pull request #4
Opened 2019-11-27 18:21 UTC by AleRousse

2019-11-27 20:16 UTC, lucasmaurice requested changes
Encore des remarques :pls:

2019-11-27 20:16 UTC, lucasmaurice commented on main.tf
> +  name             = "${var.name}${count.index + 1}"
Mais la  si t'en a qu'une t'aura forcément un name genre elastic1 ?
(Et quitte a avoir ca, j'aime mieux 01;02...)

2019-11-27 20:16 UTC, lucasmaurice commented on main.tf
> +  count            = var.instance != null ? var.instance : 1
tu peux pas mettre default a 1 dans variable ?

2019-11-27 20:16 UTC, lucasmaurice commented on main.tf
> +  name             = "${var.name}${count.index + 1}"
Mais je mettrais genre `var.instance != 1 ? ${var.name}${count.index + 1} : ${var.name}`

2019-11-27 20:16 UTC, lucasmaurice commented on main.tf
> +resource "vsphere_compute_cluster_vm_anti_affinity_rule" "cluster_vm_anti_affinity_rule" {
C'est quoi ca ?

2019-11-27 20:16 UTC, lucasmaurice commented on outputs.tf
> +output "edited_policy" {
Same, c'est quoi ?

2019-11-27 20:18 UTC, AleRousse commented on main.tf
> +resource "vsphere_compute_cluster_vm_anti_affinity_rule" "cluster_vm_anti_affinity_rule" {
Ca permet de creer une policy pour s'assurer que DRS mettre les vms sur deux host different toujours. C'est regler par la variable separated = true/false

2019-11-27 20:19 UTC, AleRousse commented on outputs.tf
> +output "edited_policy" {
Ca pemet d'afficher cluster_vm_anti_affinity_rule qui est la policy pour separer les vms sur plusieurs host

2019-11-27 20:19 UTC, AleRousse commented on main.tf
> +  count            = var.instance != null ? var.instance : 1
Nice catch c'est ce que je vais faire

2019-11-27 20:20 UTC, AleRousse commented on main.tf
> +  name             = "${var.name}${count.index + 1}"
Hmm on a toujours mis 1 chiffres a la fin même si on a juste 1 instance ca permet de grow plus facile dans l'éventualité. On peux mettre 01:02 si tu aimes mieux

2019-11-27 20:26 UTC, lucasmaurice commented on main.tf
> +  name             = "${var.name}${count.index + 1}"
Mais genre si je veux mon elastic01 avec une config differente du elastic02 je suis fourré...

2019-11-29 21:47 UTC, lucasmaurice requested changes
🚀

2019-11-29 21:49 UTC, lucasmaurice approved these changes
🚀

2019-11-29 21:50 UTC, merged